export const REQUEST_RAMPS = 'REQUEST_RAMPS';
export const SUCCESS_RAMPS = 'SUCCESS_RAMPS';
export const ERROR_RAMPS = 'ERROR_RAMPS';
export const GET_MATERIALS = 'GET_MATERIALS';
export const FILTER_BY_MATERIAL = 'FILTER_BY_MATERIAL';