export const REQUEST_RAMPS = 'REQUEST_RAMPS';
export const SUCCESS_RAMPS = 'SUCCESS_RAMPS';
export const ERROR_RAMPS = 'ERROR_RAMPS';
export const FILTER_BY_MATERIAL = 'FILTER_BY_MATERIAL';

export const REQUEST_MATERIALS = 'REQUEST_MATERIALS';
export const SUCCESS_MATERIALS = 'SUCCESS_MATERIALS';
export const ERROR_MATERIALS = 'ERROR_MATERIALS';

export const COUNT_RAMPS = 'COUNT_RAMPS';